name: ml
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - antlr-python-runtime=4.9.3
  - antlr4-python3-runtime=4.9.3
  - aom=3.6.1
  - appdirs=1.4.4
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cairo=1.18.0
  - certifi=2023.7.22
  - charset-normalizer=3.3.0
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.1.1
  - cycler=0.12.1
  - dav1d=1.2.1
  - docker-pycreds=0.4.0
  - expat=2.5.0
  - ffmpeg=6.0.0
  - filelock=3.12.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.43.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2023.9.2
  - gettext=0.21.1
  - gitdb=4.0.10
  - gitpython=3.1.37
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.8
  - graphite2=1.3.13
  - harfbuzz=8.2.1
  - icu=73.2
  - idna=3.4
  - imageio=2.31.5
  - jinja2=3.1.2
  - joblib=1.3.2
  - kiwisolver=1.4.5
  - lame=3.100
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230802.1
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libdeflate=1.19
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.0
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libopenblas=0.3.24
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=4.24.4
  - libsqlite=3.43.2
  - libtasn1=4.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libvpx=1.13.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.5
  - libzlib=1.2.13
  - llvm-openmp=17.0.3
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.4
  - nettle=3.8.1
  - networkx=3.1
  - numpy=1.26.0
  - omegaconf=2.3.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.3
  - p11-kit=0.24.1
  - packaging=23.2
  - pathtools=0.1.2
  - pcre2=10.40
  - pillow=10.0.1
  - pip=23.3.1
  - pixman=0.42.2
  - protobuf=4.24.4
  - psutil=5.9.5
  - pthread-stubs=0.4
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.11.6
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytorch=2.1.0
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.3.1
  - scipy=1.11.3
  - sentry-sdk=1.31.0
  - setproctitle=1.3.3
  - setuptools=68.2.2
  - setuptools-scm=8.0.4
  - six=1.16.0
  - smmap=3.0.5
  - svt-av1=1.7.0
  - sympy=1.12
  - threadpoolctl=3.2.0
  - tk=8.6.13
  - tomli=2.0.1
  - torchvision=0.16.0
  - tornado=6.3.3
  - tqdm=4.66.1
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - urllib3=2.0.6
  - wandb=0.15.12
  - wheel=0.41.2
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
